import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillGithub
} from 'react-icons/ai'
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'

export default function Home() {
  

  return (
    <div>
      <Head>
        <title>Chiedozie Ehileme Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 ">
         <section className=" h-screen">
          <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons"> chiedozie</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill className="cursor-pointer text-xl" />
                </li>
                <li>
                  <a className=" bg bg-gradient-to-r from-blue-500 to to-blue-400 bg-blue-500 text-white px-10 py-2 rounded-lg ml-8" href="#">Resume</a>
                  </li>
              </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-blue-500 font-medium">Chiedozie Ehileme</h2>
            <h3 className="text-2xl py-2">Computer Science Student.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Current Computer Science student with the goal of becoming a software engineer, Future CEO of Cephrius Technologies</p>
          </div>
          <div className="text-6xl flex justify-center gap-16 py-10 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-blue-500 rounded-full w-96 h-96 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
         </section>
         
         <section>
          <div className="">
            <h2 className="text-4xl py-2 ">About Me</h2>
            <p className="text-md py-2 leading-9 text-gray-800 " >
            Hey there! I'm Chiedozie, a Computer Science major hailing from Katy, Texas. Ever since I can remember, I've had this burning passion for technology, especially when it comes to computers.
            I've always been that kid who rocked it in the computer classes. Now, I want to take that passion to the next level and turn it into a full-blown career. So, I decided to dive into the exciting 
            world of software engineering. I'm starting off as a backend developer, but my ultimate goal is to become a full stack developer and land a gig at a cool corporate company. On the side, when I'm not buried in coursework, I'm working on some pretty awesome side projects. You should totally check them out on my GitHub link.
            
            <p className="text-base py-2 leading-8 text-gray-800
            ">
             Thanks for taking the time to read my story. Let's rock the tech world together!
            </p>
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 border-black border-10" >
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Side Projects</h3>
              <p className="py-2">
                Majority of my side projects are apps that I am working on using these languages and frameworks.
              </p>
              <h4 className="py-4 text-blue-600">Frameworks, Languages and tools that I use:</h4>
              <p className="text-gray-800 py-1">Visual Studio Code</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">React|React Native & Next JS</p>
              <p className="text-gray-800 py-1">Node.JS</p>
              <p className="text-gray-800 py-1">Tailwind CSS </p>
              <p className="text-gray-800 py-1">Pyhon</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">HTML & CSS </p>
              <p className="text-gray-800 py-1">Notion</p>

            </div>
          </div>
         </section>
      </main>
    </div>
  );
}
